---
- name: "Create Folder if not exist"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '755'
    state: directory
  loop:
    - "{{ ghost_quadlets_path }}"
    - "{{ ghost_data_base_path }}"
    - "{{ ghost_upload_path }}"
    - "{{ mysql_data_path }}"
    - "{{ mysql_init_path }}"

- name: Download database init
  ansible.builtin.get_url:
    url: "https://github.com/TryGhost/ghost-docker/raw/refs/heads/main/mysql-init/create-multiple-databases.sh"
    dest: "{{ mysql_init_path }}/create-multiple-databases.sh"
    mode: "755"

- name: Copy static quadlets
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ghost_quadlets_path }}/{{ item | basename }}"
    mode: '600'
  with_fileglob:
    - "files/*"

- name: Copy dynamic quadlets
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ ghost_quadlets_path }}/{{ item | basename | regex_replace('\\.j2$') }}"
    mode: '600'
  with_fileglob:
    - "templates/*"

- name: Systemd daemon Reload
  ansible.builtin.systemd_service:
    scope: user
    daemon_reload: true

- name: Start database
  ansible.builtin.systemd_service:
    scope: user
    state: restarted
    name: "{{ item }}"
  loop:
    - "ghost_database"

- name: Database healthcheck
  containers.podman.podman_container_info:
    name: ghost_database
  register: app_db_info
  until:
    - app_db_info.containers | length > 0
    - "'Health' in app_db_info.containers[0].State"
    - app_db_info.containers[0].State.Health.Status == 'healthy'
  retries: 20
  delay: 5

- name: Start application
  ansible.builtin.systemd_service:
    scope: user
    state: restarted
    daemon_reload: true
    name: "{{ item }}"
    no_block: true
  loop:
    - "ghost_activitypub_migrate"
    - "ghost_activitypub"
    - "ghost_traffic_analytics"
    - "ghost"
