---
- name: GhostCMS via Podman Quadlets
  hosts: hakase
  roles:
    - role: dogtape.ghostcms.podman
    - role: dogtape.ghostcms.database
    - role: dogtape.ghostcms.app
    - role: dogtape.ghostcms.traefik
